name: pyfloods
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - bottleneck
  - cartopy
  - dask
  - eofs
  - ipython
  - jupyter
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - pandas
  - pylint
  - scipy
  - scikit-learn
  - seaborn
  - xarray
  - windspharm
  - pip:
    - colorcet
